export const GENRES = [
  'Heavy Metal',
  'Thrash Metal',
  'Death Metal',
  'Black Metal',
  'Power Metal',
  'Symphonic Metal',
  'Nu Metal',
  'Doom Metal',
  'Gothic Metal',
  'Progressive Metal',
  'Alternative Metal',
  'Industrial Metal',
  'Speed Metal',
  'Folk Metal',
  'Groove Metal',
  'Hard Rock',
  'Metalcore',
  'Deathcore',
  'Sludge Metal',
  'Progressive Death Metal',
  'Melodic Death Metal',
  'Blackened Death Metal',
  'Rock',
  'Progressive Rock',
  'Psychedelic Rock',
  'Alternative Rock',
  'Grunge',
  'Funk Rock',
  'Punk Rock',
  'Pop Punk',
  'Blues Rock',
  'Indie Rock'
];
